### ISSUE TITLE
Handle func types (async, hot-loaded etc)

### ISSUE THREAD

**Issue by c0ze** [iron-io/functions-ui#10]
functions-ui should display the function types, and should allow to edit them.

**Comment by c0ze** [comment]
Ok, updating this, actually the ui displays function/route type (as sync / async) but doesn't display hot-functions.

**Comment by sss0350** [comment]
Hot function type should be configurable on ui.

**Comment by sss0350** [comment]
It seems there still got bugs on UI, can I change the idle_timeout time anytime on UI? I got invalid json format when click save button.

**Comment by c0ze** [comment]
@sss0350 thanks for the report ! just to make sure, you are running `0.0.2` right ?

If possible, can you please post a request body ?
