### ISSUE TITLE
Support JWT Auth

### ISSUE THREAD

**Issue by c0ze** [iron-io/functions-ui#12]
Now that [functions support JWT auth](https://github.com/iron-io/functions/releases/tag/0.2.70), we need to add this to the UI as well. @kunihiko-t what do you think ?

**Comment by kunihiko-t** [comment]
Hi, I think we need JWT support both of route level & service level.

### Route Level 
We need JWT Key field here. 
[
![app](https://user-images.githubusercontent.com/67477/34975360-d2f2228c-fad4-11e7-878f-fbc32f1990c1.png)
](url)

### Service Level

Read JWT_KEY env variable when function-ui starts up. and generate JWT for each request to the function server.
Regarding access restrictions to the UI, it's better to do it on another layer( e.g Basic Auth on Nginx)

What do you think?

**Comment by c0ze** [comment]
Regarding JWT tokens, yes, looks good ! I agree with you points !

> Regarding access restrictions to the UI, it's better to do it on another layer( e.g Basic Auth on Nginx)

Arghh yes, never though about this ! This is of course absolutely necessary as well. I'll think about it ! (You can assume this is out of scope of JWT auth) Let's handle this separately !

**Comment by kunihiko-t** [comment]
Yeah, I'll work on Route level one for now :)
