### ISSUE TITLE
Missing css- and jar-files

### ISSUE THREAD

**Issue by PLoecker** [iron-io/functions-ui#18]
Hello,
I installed the function-ui with docker and kubernetes. In both versions, there are missing the bundle file.

![image](https://user-images.githubusercontent.com/11966379/47032127-da5f7a00-d171-11e8-9fc2-6391a2bee33e.png)

![image](https://user-images.githubusercontent.com/11966379/47032143-e9dec300-d171-11e8-8ef7-bc340e4ffcc6.png)

When I open the css-file by the link I get a 404.

![image](https://user-images.githubusercontent.com/11966379/47032242-31fde580-d172-11e8-911e-b65b48a7c994.png)

Did I miss some steps?

**Comment by c0ze** [comment]
@PLoecker 

no, you didnt miss any steps. The last version is broken, please use 0.0.2.

`docker pull iron/functions-ui:0.0.2`

**Comment by PLoecker** [comment]
@c0ze 
Thank you!
Now it's running fine. A little note in the readme would be great.
