### ISSUE TITLE
UI is currently not working

### ISSUE THREAD

**Issue by atticusmiles** [iron-io/functions-ui#19]
deployed ui as in document:
```
sudo docker run --rm -d --link functions:api -p 8089:4000 -e "API_URL=http://api:8080" iron/functions-ui
```
but the page is not showing properly:
![2018-10-24 9 54 57](https://user-images.githubusercontent.com/9739352/47435798-d8cc2c80-d7d7-11e8-9c92-1bb2a73b1f20.png)

![2018-10-24 9 57 06](https://user-images.githubusercontent.com/9739352/47435725-c3ef9900-d7d7-11e8-82e0-5a72b7d685b9.png)
maybe the packaging is corrupt? It seems the page is not getting some static resources.

**Comment by c0ze** [comment]
yes, sorry the last package is broken due some incompatibility with webpack & postcss.

please use 0.0.2 version

https://github.com/iron-io/functions-ui/issues/18

thanks !
